import { Message } from '../types';

export const MODEL_CHUNK_MESSAGE_TYPE = 'model-chunk-message' as const;

export interface ModelChunkMessageData {
  content: string;
}

// Represents a chunk of a message generated by the model.
export interface ModelChunkMessage extends Message<ModelChunkMessageData> {
  type: typeof MODEL_CHUNK_MESSAGE_TYPE;
}