import { Message } from '../types';

export const MODEL_MESSAGE_TYPE = 'model-message' as const;

export interface ModelMessageData {
  content: string;
}

// Represents a message generated by the model.
export interface ModelMessage extends Message<ModelMessageData> {
  type: typeof MODEL_MESSAGE_TYPE;
}